# Generated by Django 2.1.3 on 2018-11-24 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsClosed', models.BooleanField(default=False)),
                ('Height', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Width', models.DecimalField(decimal_places=2, max_digits=9)),
                ('Weight', models.DecimalField(decimal_places=2, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('X', models.DecimalField(decimal_places=3, max_digits=9)),
                ('Y', models.DecimalField(decimal_places=3, max_digits=9)),
            ],
        ),
        migrations.AddField(
            model_name='edge',
            name='EndingNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EndingNode', to='data.Node'),
        ),
        migrations.AddField(
            model_name='edge',
            name='StartingNode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StartingNode', to='data.Node'),
        ),
    ]
