# Generated by Django 2.0.9 on 2018-11-24 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edge',
            name='Height',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='edge',
            name='Weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='edge',
            name='Width',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
