# Generated by Django 2.0.9 on 2018-11-25 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_node_uid'),
        ('data', '0002_auto_20181124_2226'),
    ]

    operations = [
    ]
